name: Build Unity Android APK

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 确保其他 Actions 也升级到最新版本

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build Android APK
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.34f1  # 确认版本号正确
          targetPlatform: Android

      - name: Upload APK
        uses: actions/upload-artifact@v4  # 修复为 v4
        with:
          name: Anon-APK
          path: build/Android/*.apk
          retention-days: 7  # 可选：限制产物保留时间
