name: Build Unity Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build Android APK
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.34f1c1  # <- 改成你自己的 Unity 版本！
          targetPlatform: Android

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Anon-APK
          path: build/Android/*.apk
